name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Specify a version that meets your needs, e.g., '3.1', '3.2', etc.
          bundler-cache: true  # This will install dependencies using the Gemfile.lock

      - name: Build and deploy
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
